FROM node:16-alpine

ARG BUILD_ENVIRONMENT="staging"
ARG CI_PIPELINE_IID
ARG NEXT_PUBLIC_SENTRY_AUTH_TOKEN
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_RELEASE
ARG NEXT_PUBLIC_SENTRY_ENVIRONMENT

ADD . /src
WORKDIR /src
ENV ENVIRONMENT=${BUILD_ENVIRONMENT}
ENV NEXT_PUBLIC_SENTRY_AUTH_TOKEN=${NEXT_PUBLIC_SENTRY_AUTH_TOKEN}
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ENV NEXT_PUBLIC_SENTRY_RELEASE=${NEXT_PUBLIC_SENTRY_RELEASE}
ENV NEXT_PUBLIC_SENTRY_ENVIRONMENT=${NEXT_PUBLIC_SENTRY_ENVIRONMENT}
RUN env

RUN JOBS=max yarn install
RUN JOBS=max yarn run build:${ENVIRONMENT}

CMD yarn serve
